/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "llamojhaamplify-20201025200737-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://llamojhaamplify-20201025200737-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
